#!/bin/bash -e

set -u

echo "post-install"

if [[ -e $APP_HOME/fail-post-install ]]
then
  echo "Simulating failure."
  exit 1
fi

NAME=`basename $APP_HOME`

if [ -d root/etc/$NAME ]
then
  find root/etc/$NAME -maxdepth 1 -type f | while read file
  do
    cp $file root/
  done
fi

[ -d ../../logs ] || mkdir ../../logs

ln -s ../../../logs root/logs
