#!/bin/bash

set -e
set -u

APPMGR_HOME=$(dirname "$0")
APPMGR_HOME=$(cd "$APPMGR_HOME/../.." && pwd)
export APPMGR_HOME

. "$APPMGR_HOME/share/appmgr/common"
# HEADER END

usage_text() {
  echo "usage: $usage_app <-l user> -v [version] -h [hook]"
}

version=
hook=
location=

while getopts "v:h:l:" opt
do
  case $opt in
    v)
      version=$OPTARG
      shift 2
      OPTIND=1
      ;;
    h)
      hook=$OPTARG
      shift 2
      OPTIND=1
      ;;
    l)
      location=$OPTARG
      shift 2
      OPTIND=1
      ;;
  esac
done

if [[ -z $version || -z $hook || $# != 0 ]]
then
  usage
fi

if [[ ! -z $location && $location != "user" ]]
then
  usage
fi

if [[ ! -z $location ]]
then
  bin="$HOME/.app/hooks/$hook"
  exe="$bin"
else
  bin="versions/$version/hooks/$hook"
  exe="hooks/$hook"
fi

if [[ ! -r $bin ]]
then
  exit 0
fi

# TODO: remove
chmod +x "$bin"

if [[ ! -e $bin ]]
then
  info "Not executable: $bin"
  exit 0
fi

debug "Running hook: $hook"
run_app -v "$version" "$exe"
