#!/bin/bash

set -e
set -u

APPSH_HOME=$(cd $(dirname "$0")/.. && pwd)

. $APPSH_HOME/lib/common
# HEADER END

key_expr="[a-zA-Z][_a-zA-Z0-9]*"

files=()
name=""
use_default_files=yes

while getopts "f:Dn:" opt
do
  case $opt in
    f)
      file=$OPTARG
      if [[ $file == "-" ]]
      then
        file=/dev/stdin
      fi
      files+=($file)
      ;;
    D)
      use_default_files=no
      ;;
    n)
      name=$OPTARG
      ;;
    \?)
      echo "Invalid option: $OPTARG" >&2
      exit 1
      ;;
  esac
done

if [[ $use_default_files == yes ]]
then
  app_home=${APP_HOME-.}
  if [ -r "$app_home/.app/config" ]
  then
    files+=("$app_home/.app/config")
  fi

  files+=(${APPSH_DEFAULT_CONFIG-$APPSH_HOME/lib/default-config})
fi

# TODO: find config files in the paths above $file's paths and perhaps
# /etc/appsh/config.

if [ -z "$name" ]
then
  filter="s,^[ ]*\($key_expr\.$key_expr\)[ ]*=[ ]*\(.*\)$,\1=\2,p"
else
  filter="s,^\($name\)=\(.*\),\1=\2,p"
fi

debug "Using files:" "${files[@]}"

# The awk script makes sure each key only appears once. The first one wins
cat "${files[@]}" | \
  sed -n -e "$filter" | \
  awk -F = ' (!($1 in a)){a[$1]; print }' | \
  sort
