#!/bin/bash

set -e
set -u

APPMGR_HOME=$(dirname "$0")
APPMGR_HOME=$(cd "$APPMGR_HOME/.." && pwd)
export APPMGR_HOME

. "$APPMGR_HOME/lib/common"
# HEADER END

assert_is_app

method="$1"; shift

bin=$(app-conf get app.operator)
bin=${bin:-$APPMGR_HOME/libexec/app-operator-pid}

if [ ! -x "$bin" ]
then
  fatal "Invalid executable: $bin" >&2
fi

run_app "$bin" "$method" "$@"
