#!/bin/bash

set -e
set -u

APPSH_HOME=$(cd $(dirname "$0")/.. && pwd)

. $APPSH_HOME/lib/common
# HEADER END

assert_is_app

method="$1"; shift
set -x

bin=`app-conf get app.operator`
bin=${bin:-$APPSH_HOME/libexec/app-operator-pid}

if [ ! -x "$bin" ]
then
  echo "Invalid executable: $bin" >&2
  exit 1
fi

run_app "$bin" "$@"
