#!/bin/bash -e

echo "Hello World!"

if [ -d etc/$APPSH_INSTANCE ]
then
  find etc/$APPSH_INSTANCE -type f -maxdepth 1 | while read file
  do
    cp $file .
  done
fi

LOGS=$APPSH_APPS/$APPSH_NAME/$APPSH_INSTANCE/logs

if [ ! -d $LOGS ]
then
  echo "Creating logs directory"
  mkdir $LOGS
fi

ln -s $LOGS logs
